### ISSUE TITLE
You forgot your Mapbox token in sources 

### ISSUE THREAD

**Issue by rtouze** [EduardoMateos/vue-widget-mondial-relay#3]
Hi,
I came here because I'm also building a map component to interact with Mondial Relay. I noticed you forgot to remove your mapbox token from the [sources](https://github.com/EduardoMateos/vue-widget-mondial-relay/blob/3577fde76700593e61863a670ed5e997634abfe8/src/components/LMap.vue#L34)

**Comment by EduardoMateos** [comment]
Hi!

I took that token from a leaflet example:

https://github.com/Leaflet/Leaflet/blob/master/docs/examples/quick-start/example-overlays.md

I don't know if I can use it, I'll investigate it! Thanks

I started developing this package a few days ago (I don't like jQuery 2) I need time to finish it. Feel free to use it however you want.
